# This workflow is for code quality checks and tests.
name: Code Quality

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    pylint:
        runs-on: ubuntu-latest
        steps: # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Install dependencies
              run: uv sync --frozen --dev -p 3.13
              id: uv-sync

            - name: Run pylint
              run: uv run --dev pylint --verbose clipea

    ruff:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: lint
              run: uv run --dev ruff check ./clipea ./tests

            - name: format
              run: uv run --dev ruff format --check ./clipea ./tests

    pytest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.13"]
        steps: # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Install dependencies
              run: uv sync --frozen --dev --python ${{ matrix.python-version }}
              id: uv-sync

            - name: Run pytest
              run: uv run --dev --python ${{ matrix.python-version }} pytest
